version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=choice_app
    command: mongod --bind_ip 0.0.0.0

volumes:
  mongodb_data: 